server:
  port: 8082

spring:
  application:
    name: microservice-email
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jap:
    hibernate:
      ddl-auto: update

