server:
  port: 8081

spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jap:
    hibernate:
      ddl-auto: update
