server:
  port: 8081

spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: "amqps://ewlftsee:D4Nu9C784y1BcVAa61yHeOnXK5e56xbe@armadillo.rmq.cloudamqp.com/ewlftsee"

broker:
  queue:
    email:
      name: default.email
