server:
  port: 8081

spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: "amqps://fkmqvjdt:TCfpj63dxTsNMiVrZctEkrXqSnJiD4fl@possum.lmq.cloudamqp.com/fkmqvjdt"

broker:
  queue:
    email:
      name: default.email
